/**
 * Derive machine-checkable ground truth from the datasheets themselves.
 *
 * WHY THIS IS NOT LEAKAGE. The label is produced by a deterministic parser over
 * the PDF text layer. The system under test embeds, retrieves across ~700
 * near-identical documents, reranks, and extracts with an LLM. Different
 * mechanism, so the label is independent of the thing it grades. This is how
 * DocVQA and TAT-QA are built. Leakage would mean labels generated BY the model
 * being graded, or a retriever that has seen the test set. Neither happens here.
 *
 * THE ANCHOR. Every Nexperia MOSFET datasheet carries a "Quick reference data"
 * table with a fixed column shape, stable from a 2011 datasheet (PMV45EN) to a
 * 2023 one (PSMN1R0-30YLD):
 *
 *   Symbol   Parameter              Conditions              Min  Typ  Max  Unit
 *   VDS      drain-source voltage   25 C <= Tj <= 175 C      -    -   30   V
 *   RDSon    drain-source on-state  VGS = 10 V; Tj = 100 C   -  19.4  25   mOhm
 *                                   VGS = 10 V; Tj = 25 C    -  10.8 13.9  mOhm
 *
 * ROW ORDER IS NOT STABLE, AND THAT MATTERS. PSMN013-100BS quotes its 100 C row
 * FIRST (25 mOhm) and its 25 C row second (13.9 mOhm). Taking "the first RDSon
 * row" silently grades a 25 C question against a 100 C number. So RDSon is
 * selected by CONDITION, not by position, and the condition travels with the
 * label into the question text. An unconditioned RDSon question is ill-posed.
 *
 * CROSS-VALIDATION IS FREE. Nexperia part numbers encode the nominal figures:
 * BUK7K5R1-30E is 5.1 mOhm / 30 V, PSMN1R0-30YLD is 1.0 mOhm / 30 V. That
 * naming convention is a third mechanism, independent of both the PDF table and
 * the RAG, so `--check` grades the parser against it across the whole corpus
 * rather than against a hand-labelled sample of thirty.
 */

import { readdirSync } from "node:fs";

export type Measurement = {
  /** The Max column. This is the guaranteed figure and the one we grade against. */
  value: number;
  /** The Typ column. Kept because the part-number convention encodes typ, not max. */
  typ: number | null;
  unit: string;
  conditions: string;
};

export type GroundTruth = {
  part: string;
  channel: "N" | "P";
  package: string | null;
  /**
   * Drain-source voltage in V, SIGNED as the datasheet prints it. A P-channel
   * part quotes -30 V and the label says -30.
   *
   * This used to be `Math.abs(...)`, and the magnitude looked like the tidier
   * choice: the spec people quote out loud is "a 30 V part". It cost three
   * questions in the first eval, where the system read the document correctly,
   * answered "-30 V", and was marked wrong. A label that disagrees with the
   * document it was parsed from is not a label. The grader compares magnitudes
   * and reports polarity separately, so nothing is lost by telling the truth here.
   */
  vds_v: number | null;
  /** Continuous drain current in A, signed as printed. Same story as vds_v. */
  id_a: Measurement | null;
  /** Max on-state resistance in mOhm at the standard Tj = 25 C reference condition. */
  rdson_mohm: Measurement | null;
};

const PACKAGES = [
  "LFPAK88", "LFPAK56D", "LFPAK56E", "LFPAK56", "LFPAK33", "CFP15", "CFP3", "CFP2",
  "D2PAK", "DPAK", "TO-220AB", "TO-220", "TO-247", "TO-263", "SOT1289", "SOT669",
  "SOT428", "SOT404", "SOT223", "SOT23", "SOT89", "SOT78", "SO8", "TSOP6"
];

// A data row ends with: Min Typ Max Unit. Each value is a number or a bare "-".
// Anchoring at end-of-line is what stops a trailing figure reference ("Fig. 10")
// in the conditions column from being read as a value.
const TAIL = /(-?\d+(?:\.\d+)?|-)\s+(-?\d+(?:\.\d+)?|-)\s+(-?\d+(?:\.\d+)?|-)\s+(\S+)\s*$/;

// A new table row starts with a symbol: an uppercase-led token, then whitespace,
// then a lowercase parameter name. Continuation rows have neither.
const NEW_SYMBOL = /^[A-Z][A-Za-z0-9()]*\s+[a-z]/;

const SECTION = /^(Static|Dynamic|Thermal|Limiting|Symbol|Table|Nexperia)\b/;

type Row = { text: string; min: string; typ: string; max: string; unit: string };

/** Every data row belonging to `symbol`, including its wrapped continuation rows. */
function rowsFor(lines: string[], symbol: string): Row[] {
  const rows: Row[] = [];
  let inBlock = false;

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) continue;

    const startsBlock = line.startsWith(symbol) && /^\s/.test(line.slice(symbol.length));

    if (startsBlock) {
      inBlock = true;
    } else if (inBlock && (SECTION.test(line) || NEW_SYMBOL.test(line))) {
      inBlock = false;
    }
    if (!inBlock) continue;

    const match = TAIL.exec(line);
    if (!match) continue;
    rows.push({ text: line, min: match[1], typ: match[2], max: match[3], unit: match[4] });
  }

  // The table can repeat its header across a page break, so the same row can be
  // seen twice. Identical (conditions, values) is a duplicate, not a data point.
  const seen = new Set<string>();
  return rows.filter((row) => {
    const key = `${row.text.replace(/\s+/g, " ")}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function num(field: string): number | null {
  if (field === "-") return null;
  const value = Number(field);
  return Number.isFinite(value) ? value : null;
}

/**
 * Pull the measurement conditions out of a row.
 *
 * Extracting the `SYMBOL = value` clauses directly beats stripping the prose
 * around them: the parameter name wraps unpredictably across lines, so a
 * strip-based approach leaves fragments ("on VGS = 10 V", "current VGS = ...").
 */
const CONDITION = /\b(VGS|VDS|ID|Tj|Tmb|Tsp|Tamb|IDM|f)\s*=\s*[-\d.]+\s*[^\s;]*/g;

function conditions(text: string): string {
  const clauses = [...text.matchAll(CONDITION)].map((m) => m[0].trim());
  return clauses.join("; ");
}

/** True when a row is quoted at the standard 25 C reference junction temperature. */
function isReferenceTemp(text: string): boolean {
  return /Tj\s*=\s*25/.test(text);
}

/** The gate drive a row is measured at, in volts. */
function gateDrive(text: string): number | null {
  const match = /VGS\s*=\s*(-?[\d.]+)/.exec(text);
  return match ? Math.abs(Number(match[1])) : null;
}

export function parseDatasheet(part: string, text: string): GroundTruth | null {
  const start = text.indexOf("Quick reference data");
  if (start === -1) return null;

  const head = text.slice(0, 4000);
  const table = text.slice(start, start + 8000).split("\n");

  const channel: "N" | "P" | null = /N-channel/i.test(head)
    ? "N"
    : /P-channel/i.test(head)
      ? "P"
      : null;
  if (!channel) return null;

  const vdsRows = rowsFor(table, "VDS").filter((r) => r.unit === "V");
  const idRows = rowsFor(table, "ID").filter((r) => r.unit === "A");
  const rdsonRows = rowsFor(table, "RDSon").filter((r) => /^m?[ΩΩ]/.test(r.unit) || r.unit === "mΩ");

  // Select RDSon by condition, never by position: see the header note.
  // Select the RDSon row by CONDITION, never by position. Two things vary
  // across the corpus and both change the answer by more than 2x:
  //   - row order (PSMN013-100BS quotes Tj = 100 C before Tj = 25 C)
  //   - gate drive (a part with 4.5 V and 10 V rows reads ~1.6x higher at 4.5 V)
  // We pin to the industry reference condition, VGS = 10 V at Tj = 25 C, and
  // fall back to the strongest available gate drive at 25 C. The chosen
  // conditions travel with the label into the question, so a part that only
  // publishes a 4.5 V figure still yields a well-posed question.
  const atRefTemp = rdsonRows.filter((r) => isReferenceTemp(r.text));
  const byGateDrive = [...atRefTemp].sort((a, b) => (gateDrive(b.text) ?? 0) - (gateDrive(a.text) ?? 0));
  const rdsonRow =
    atRefTemp.find((r) => gateDrive(r.text) === 10) ?? byGateDrive[0] ?? rdsonRows[0];
  let rdson: Measurement | null = null;
  if (rdsonRow) {
    const max = num(rdsonRow.max);
    if (max !== null) {
      const milli = rdsonRow.unit.startsWith("m");
      const scale = milli ? 1 : 1000;
      const typ = num(rdsonRow.typ);
      rdson = {
        value: max * scale,
        typ: typ === null ? null : typ * scale,
        unit: "mΩ",
        conditions: conditions(rdsonRow.text)
      };
    }
  }

  const vdsMax = vdsRows[0] ? num(vdsRows[0].max) : null;
  const idMax = idRows[0] ? num(idRows[0].max) : null;

  return {
    part,
    channel,
    package: PACKAGES.find((name) => head.includes(name)) ?? null,
    // Signed, as printed. A P-channel part reads -30 V and the label says so.
    vds_v: vdsMax,
    id_a:
      idMax === null || !idRows[0]
        ? null
        : {
            value: idMax,
            typ: null,
            unit: "A",
            conditions: conditions(idRows[0].text)
          },
    rdson_mohm: rdson
  };
}

/**
 * Decode the nominal RDSon and VDS a Nexperia part number encodes.
 * BUK7K5R1-30E -> 5.1 mOhm, 30 V.   PSMN013-100BS -> 13 mOhm, 100 V.
 * Returns null for the naming schemes that do not carry the convention.
 */
export function decodeName(part: string): { rdson_mohm: number; vds_v: number } | null {
  // 1R0-30, 5R1-30, 4R0-40: the R is the decimal point and takes exactly ONE
  // digit in front of it. The family prefix is variable-length, so a greedy
  // \d+R\d+ reads BUK764R0-40E as 764 milliohm instead of 4.0 — a 190x error
  // that looked like a parser bug and was not one.
  const decimal = /(\d)R(\d+)-(\d+)/.exec(part);
  if (decimal) {
    return {
      rdson_mohm: Number(`${decimal[1]}.${decimal[2]}`),
      vds_v: Number(decimal[3])
    };
  }
  // R90-80, R58-30: sub-milliohm parts drop the leading zero, so the R sits
  // directly against the family prefix and R90 means 0.90 mOhm. The integer rule
  // below reads that same string as 90 mOhm, and the cross-check then reported a
  // 100x disagreement (PSMNR90-80CSF: "name 90 mΩ · table 0.9 mΩ") as if the
  // table parser had failed. It had not. The check was wrong about the name.
  const subMilli = /R(\d+)-(\d+)/.exec(part);
  if (subMilli && !/\dR\d/.test(part)) {
    return { rdson_mohm: Number(`0.${subMilli[1]}`), vds_v: Number(subMilli[2]) };
  }
  // 013-100: an integer milliohm figure. No \b after the voltage — a trailing
  // package suffix (PSMN013-100BS) is a word character, so \b never matches and
  // the whole integer family silently drops out of the cross-check.
  const integer = /^[A-Z]+(\d{2,3})-(\d{2,3})/.exec(part);
  if (integer) {
    return { rdson_mohm: Number(integer[1]), vds_v: Number(integer[2]) };
  }
  return null;
}

if (import.meta.main) {
  const dir = process.argv[2];
  const check = process.argv.includes("--check");
  if (!dir) {
    console.error("usage: bun tools/groundtruth.ts <corpus-dir> [--check] > groundtruth.json");
    process.exit(1);
  }

  const pdfs = readdirSync(dir).filter((name) => name.endsWith(".pdf"));
  const rows: GroundTruth[] = [];
  let unparsed = 0;

  for (const pdf of pdfs) {
    const part = pdf.replace(/\.pdf$/, "");
    const text = await Bun.$`pdftotext -layout ${`${dir}/${pdf}`} -`.quiet().text();
    const parsed = parseDatasheet(part, text);
    if (!parsed) {
      unparsed++;
      continue;
    }
    rows.push(parsed);
  }

  const has = (fn: (r: GroundTruth) => unknown) => rows.filter(fn).length;
  console.error(`${pdfs.length} pdfs — ${rows.length} parsed, ${unparsed} no quick-reference table`);
  console.error(
    `coverage: vds ${has((r) => r.vds_v)} · rdson ${has((r) => r.rdson_mohm)}` +
      ` · id ${has((r) => r.id_a)} · package ${has((r) => r.package)}`
  );
  console.error(
    `rdson at reference temp: ${has((r) => r.rdson_mohm && /Tj\s*=\s*25/.test(r.rdson_mohm.conditions))}`
  );

  if (check) {
    // Grade the PDF-table parser against the part-number naming convention: a
    // third mechanism, independent of both the table and the RAG.
    //
    // The name encodes the MAX figure (BUK7Y3R5-40E: typ 2.5, max 3.5, name
    // 3R5). The residual disagreements are NOT parser errors — they are parts
    // whose datasheet quotes several VGS rows at Tj = 25 C, where the name
    // refers to a different gate drive than the row we selected. That ambiguity
    // is exactly why the label carries its conditions and the question text
    // repeats them: an unconditioned RDSon question has no single right answer.
    let checked = 0;
    let vdsAgree = 0;
    let rdsonAgree = 0;
    const disagreements: string[] = [];

    for (const row of rows) {
      const named = decodeName(row.part);
      if (!named || !row.rdson_mohm || row.vds_v === null) continue;
      checked++;

      // Magnitudes: the part number encodes "30 V" for a part whose table prints
      // -30 V. The name has no polarity to carry, so comparing signed values here
      // would report every P-channel part as a parser disagreement.
      if (Math.abs(row.vds_v) === named.vds_v) vdsAgree++;

      const max = row.rdson_mohm.value;
      const ok = Math.abs(max - named.rdson_mohm) / named.rdson_mohm <= 0.1;
      if (ok) rdsonAgree++;
      else if (disagreements.length < 12) {
        disagreements.push(
          `${row.part}: name ${named.rdson_mohm} mΩ · table max ${max} mΩ · ` +
            `[${row.rdson_mohm.conditions}]`
        );
      }
    }

    const pct = (n: number) => ((n / checked) * 100).toFixed(1);
    console.error(`\nname cross-check over ${checked} decodable part numbers:`);
    console.error(`  VDS   ${vdsAgree}/${checked} (${pct(vdsAgree)}%)`);
    console.error(`  RDSon ${rdsonAgree}/${checked} (${pct(rdsonAgree)}%) — name vs table max, 10% band`);
    for (const line of disagreements) console.error(`  ! ${line}`);
  }

  console.log(JSON.stringify(rows, null, 2));
}
