/**
 * Derive machine-checkable ground truth from the datasheets themselves.
 *
 * WHY THIS IS NOT LEAKAGE. The label is produced by a deterministic parser over
 * the PDF text layer. The system under test embeds, retrieves across ~700
 * near-identical documents, reranks, and extracts with an LLM. Different
 * mechanism, so the label is independent of the thing it grades. This is how
 * DocVQA and TAT-QA are built. Leakage would mean labels generated BY the model
 * being graded, or a retriever that has seen the test set. Neither happens here.
 *
 * THE ANCHOR. Every Nexperia MOSFET datasheet carries a "Quick reference data"
 * table with a fixed column shape, stable from a 2011 datasheet (PMV45EN) to a
 * 2023 one (PSMN1R0-30YLD):
 *
 *   Symbol   Parameter              Conditions              Min  Typ  Max  Unit
 *   VDS      drain-source voltage   25 C <= Tj <= 175 C      -    -   30   V
 *   RDSon    drain-source on-state  VGS = 10 V; Tj = 100 C   -  19.4  25   mOhm
 *                                   VGS = 10 V; Tj = 25 C    -  10.8 13.9  mOhm
 *
 * ROW ORDER IS NOT STABLE, AND THAT MATTERS. PSMN013-100BS quotes its 100 C row
 * FIRST (25 mOhm) and its 25 C row second (13.9 mOhm). Taking "the first RDSon
 * row" silently grades a 25 C question against a 100 C number. So RDSon is
 * selected by CONDITION, not by position, and the condition travels with the
 * label into the question text. An unconditioned RDSon question is ill-posed.
 *
 * CROSS-VALIDATION IS FREE. Nexperia part numbers encode the nominal figures:
 * BUK7K5R1-30E is 5.1 mOhm / 30 V, PSMN1R0-30YLD is 1.0 mOhm / 30 V. That
 * naming convention is a third mechanism, independent of both the PDF table and
 * the RAG, so `--check` grades the parser against it across the whole corpus
 * rather than against a hand-labelled sample of thirty.
 */

import { readdirSync } from "node:fs";

export type Measurement = {
  /** The Max column. This is the guaranteed figure and the one we grade against. */
  value: number;
  /** The Typ column. Kept because the part-number convention encodes typ, not max. */
  typ: number | null;
  unit: string;
  conditions: string;
};

export type GroundTruth = {
  part: string;
  channel: "N" | "P";
  /** Every name the ordering table prints for this part's package. See `packageOf`. */
  package: string[] | null;
  /**
   * Drain-source voltage in V, SIGNED as the datasheet prints it. A P-channel
   * part quotes -30 V and the label says -30.
   *
   * This used to be `Math.abs(...)`, and the magnitude looked like the tidier
   * choice: the spec people quote out loud is "a 30 V part". It cost three
   * questions in the first eval, where the system read the document correctly,
   * answered "-30 V", and was marked wrong. A label that disagrees with the
   * document it was parsed from is not a label. The grader compares magnitudes
   * and reports polarity separately, so nothing is lost by telling the truth here.
   */
  vds_v: number | null;
  /** Continuous drain current in A, signed as printed. Same story as vds_v. */
  id_a: Measurement | null;
  /** Max on-state resistance in mOhm at the standard Tj = 25 C reference condition. */
  rdson_mohm: Measurement | null;
};

/**
 * Where the datasheet actually STATES the package: the Ordering information table.
 *
 *   Type number      Package
 *                    Name       Description                          Version
 *   PSMN012-100YS    LFPAK      plastic single-ended package; ...    SOT669
 *
 * This used to be a hand-written list of package names scanned against the first
 * 4000 characters of the document, taking the first name in LIST order that
 * appeared anywhere in that slab. Two things were wrong with it, and they
 * compounded.
 *
 * The list did not contain `LFPAK` (only `LFPAK56`, `LFPAK33`, …), so the one name
 * PSMN012-100YS actually uses could not be found. What the scan found instead was
 * `SO8`, from a MARKETING BULLET on the front page: "LFPAK provides maximum power
 * density in a Power SO8 package". The label for that part became SO8. The model
 * read the title and the ordering table, answered LFPAK, and was marked wrong.
 *
 * And the list was silently incomplete in the other direction: `DFN2020MD-6`,
 * `CCPAK1212i` and `MLPAK33` were not in it, so 165 parts got NO package label and
 * therefore no package question. The benchmark was not testing them at all.
 *
 * Third time in this file that the label read a SUMMARY surface — the quick-
 * reference extract, the marketing bullet — while the model read the authoritative
 * one. The rule that falls out: parse the table that states the fact, never the
 * prose that mentions it.
 *
 * A package has several true names. The Name column may hold two (`LFPAK56;
 * Power-SO8`, sometimes wrapped onto the next line) and the Version column is a
 * third (`SOT669`). All of them are printed by Nexperia, on one row, for one
 * package, and an engineer answers with whichever is in front of them. So the
 * label is a LIST, and the grader accepts any member.
 */
const PACKAGE_NAME = /^[A-Z][A-Za-z0-9‐-―-]*$/;
const PACKAGE_VERSION = /\b(SOT\d+[A-Z]?)\b/;

function packageOf(text: string, part: string): string[] | null {
  const at = text.indexOf("Ordering information");
  if (at === -1) return null;

  const lines = text.slice(at, at + 2500).split("\n");
  const escaped = part.replace(/[-.]/g, "\\$&");
  const rowAt = lines.findIndex((line) => new RegExp(`^\\s*${escaped}\\s`).test(line));
  if (rowAt === -1) return null;

  const row = lines[rowAt];
  const tokens = row.slice(row.indexOf(part) + part.length).trim().split(/\s+/);

  const name = tokens[0]?.replace(/;$/, "") ?? "";
  if (!PACKAGE_NAME.test(name)) return null;

  const names = [name];

  // A trailing semicolon promises a second name — on this row, or wrapped onto the
  // next. It must carry a digit: the token after the name is otherwise the start of
  // the Description column, and "Plastic" is not a package.
  if (tokens[0].endsWith(";")) {
    const candidates = [tokens[1], lines[rowAt + 1]?.trim().split(/\s+/)[0]];
    const alias = candidates.find((t) => t && PACKAGE_NAME.test(t) && /\d/.test(t));
    if (alias) names.push(alias);
  }

  const version = PACKAGE_VERSION.exec(row)?.[1] ?? PACKAGE_VERSION.exec(lines[rowAt + 1] ?? "")?.[1];
  if (version && !names.includes(version)) names.push(version);

  return names;
}

// A data row ends with its value columns and then a unit. Each value is a number
// or a bare "-". Anchoring at end-of-line is what stops a trailing figure
// reference ("Fig. 10") in the conditions column from being read as a value.
//
// TWO or three columns, because the datasheet uses both and this pattern used to
// insist on three. Quick reference data prints Min Typ Max; Limiting values prints
// only Min Max. So a three-column pattern silently cannot match a single row of
// the Limiting values table, and every label this file has ever produced came from
// the Quick reference table alone — which the datasheet itself calls "an extract of
// the product data given in the Limiting values and Characteristics sections". The
// label was reading the summary while the model read the source, and where the two
// disagree (a 5-second rating in the extract, a continuous one in the real table)
// the model was marked wrong for reading the better document.
const TAIL = /((?:(?:-?\d+(?:\.\d+)?|-)\s+){2,3})(\S+)\s*$/;

/** Min, typ and max out of a row's value columns. Typ is absent in a two-column table. */
function columns(row: string): { min: string; typ: string; max: string } {
  const match = TAIL.exec(row);
  if (!match) throw new Error(`not a data row: ${row}`);
  const values = match[1].trim().split(/\s+/);
  return {
    min: values[0],
    typ: values.length === 3 ? values[1] : "-",
    max: values[values.length - 1]
  };
}

// A new table row starts with a symbol: an uppercase-led token, then whitespace,
// then a lowercase parameter name. Continuation rows have neither.
const NEW_SYMBOL = /^[A-Z][A-Za-z0-9()]*\s+[a-z]/;

const SECTION = /^(Static|Dynamic|Thermal|Limiting|Symbol|Table|Nexperia)\b/;

type Row = { text: string; min: string; typ: string; max: string; unit: string };

/** Every data row belonging to `symbol`, including its wrapped continuation rows. */
function rowsFor(lines: string[], symbol: string): Row[] {
  const rows: Row[] = [];
  let inBlock = false;

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) continue;

    const startsBlock = line.startsWith(symbol) && /^\s/.test(line.slice(symbol.length));

    if (startsBlock) {
      inBlock = true;
    } else if (inBlock && (SECTION.test(line) || NEW_SYMBOL.test(line))) {
      inBlock = false;
    }
    if (!inBlock) continue;

    const match = TAIL.exec(line);
    if (!match) continue;
    rows.push({ text: line, ...columns(line), unit: match[2] });
  }

  // The table can repeat its header across a page break, so the same row can be
  // seen twice. Identical (conditions, values) is a duplicate, not a data point.
  const seen = new Set<string>();
  return rows.filter((row) => {
    const key = `${row.text.replace(/\s+/g, " ")}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function num(field: string): number | null {
  if (field === "-") return null;
  const value = Number(field);
  return Number.isFinite(value) ? value : null;
}

/**
 * Pull the measurement conditions out of a row.
 *
 * Extracting the `SYMBOL = value` clauses directly beats stripping the prose
 * around them: the parameter name wraps unpredictably across lines, so a
 * strip-based approach leaves fragments ("on VGS = 10 V", "current VGS = ...").
 */
const CONDITION = /\b(VGS|VDS|ID|Tj|Tmb|Tsp|Tamb|IDM|f)\s*=\s*[-\d.]+\s*[^\s;]*/g;

/**
 * A duration limit is a condition, and dropping it changes which row you are
 * talking about.
 *
 * This clause is not of the form `SYMBOL = value`, so the regex above never saw
 * it, and the label went out carrying only `VGS = 10 V; Tamb = 25 °C`. But the
 * datasheet lists ID at those conditions TWICE: once for t <= 5 s and once with
 * no time limit at all, and the two are different currents. The question then
 * quoted the truncated conditions and asked for the continuous rating while the
 * label held the 5-second one, so a model reading the datasheet correctly was
 * marked wrong. The benchmark was asking about one row and grading against another.
 */
const DURATION = /\bt\s*[≤<]=?\s*[\d.]+\s*\w+/;

function conditions(text: string): string {
  const clauses = [...text.matchAll(CONDITION)].map((m) => m[0].trim());
  const limit = DURATION.exec(text);
  return [...clauses, ...(limit ? [limit[0].trim()] : [])].join("; ");
}

/** Quoted at the 25 C reference temperature, whichever temperature the part uses. */
function isReferenceAmbient(text: string): boolean {
  return /T(amb|mb|j)\s*=\s*25/.test(text);
}

/** A row with no duration limit is the continuous rating. With one, it is not. */
function isContinuous(text: string): boolean {
  return !DURATION.test(text);
}

/** True when a row is quoted at the standard 25 C reference junction temperature. */
function isReferenceTemp(text: string): boolean {
  return /Tj\s*=\s*25/.test(text);
}

/** The gate drive a row is measured at, in volts. */
function gateDrive(text: string): number | null {
  const match = /VGS\s*=\s*(-?[\d.]+)/.exec(text);
  return match ? Math.abs(Number(match[1])) : null;
}

export function parseDatasheet(part: string, text: string): GroundTruth | null {
  const start = text.indexOf("Quick reference data");
  if (start === -1) return null;

  const head = text.slice(0, 4000);
  const table = text.slice(start, start + 8000).split("\n");

  const channel: "N" | "P" | null = /N-channel/i.test(head)
    ? "N"
    : /P-channel/i.test(head)
      ? "P"
      : null;
  if (!channel) return null;

  const vdsRows = rowsFor(table, "VDS").filter((r) => r.unit === "V");
  const idRows = rowsFor(table, "ID").filter((r) => r.unit === "A");
  const rdsonRows = rowsFor(table, "RDSon").filter((r) => /^m?[ΩΩ]/.test(r.unit) || r.unit === "mΩ");

  // Select RDSon by condition, never by position: see the header note.
  // Select the RDSon row by CONDITION, never by position. Two things vary
  // across the corpus and both change the answer by more than 2x:
  //   - row order (PSMN013-100BS quotes Tj = 100 C before Tj = 25 C)
  //   - gate drive (a part with 4.5 V and 10 V rows reads ~1.6x higher at 4.5 V)
  // We pin to the industry reference condition, VGS = 10 V at Tj = 25 C, and
  // fall back to the strongest available gate drive at 25 C. The chosen
  // conditions travel with the label into the question, so a part that only
  // publishes a 4.5 V figure still yields a well-posed question.
  const atRefTemp = rdsonRows.filter((r) => isReferenceTemp(r.text));
  const byGateDrive = [...atRefTemp].sort((a, b) => (gateDrive(b.text) ?? 0) - (gateDrive(a.text) ?? 0));
  const rdsonRow =
    atRefTemp.find((r) => gateDrive(r.text) === 10) ?? byGateDrive[0] ?? rdsonRows[0];
  let rdson: Measurement | null = null;
  if (rdsonRow) {
    const max = num(rdsonRow.max);
    if (max !== null) {
      const milli = rdsonRow.unit.startsWith("m");
      const scale = milli ? 1 : 1000;
      const typ = num(rdsonRow.typ);
      rdson = {
        value: max * scale,
        typ: typ === null ? null : typ * scale,
        unit: "mΩ",
        conditions: conditions(rdsonRow.text)
      };
    }
  }

  const vdsMax = vdsRows[0] ? num(vdsRows[0].max) : null;

  // Select the ID row by CONDITION, never by position, for exactly the reason
  // RDSon already is. A datasheet lists the drain current several times: at the
  // reference temperature and at 100 C, and — where the part has one — with and
  // without a 5-second duration limit. Taking the first row took whichever the
  // typesetter happened to print first, which is the t <= 5 s figure, and that is
  // not the current the part can carry continuously.
  const idRow =
    idRows.find((r) => isReferenceAmbient(r.text) && isContinuous(r.text)) ??
    idRows.find((r) => isReferenceAmbient(r.text)) ??
    idRows[0];
  const idMax = idRow ? num(idRow.max) : null;

  return {
    part,
    channel,
    package: packageOf(text, part),
    // Signed, as printed. A P-channel part reads -30 V and the label says so.
    vds_v: vdsMax,
    id_a:
      idMax === null || !idRow
        ? null
        : {
            value: idMax,
            typ: null,
            unit: "A",
            // The FULL conditions of the row the value came from, duration limit
            // included. The question quotes these back, so a truncation here is a
            // question about a row that is not the row being graded.
            conditions: conditions(idRow.text)
          },
    rdson_mohm: rdson
  };
}

/**
 * Decode the nominal RDSon and VDS a Nexperia part number encodes.
 * BUK7K5R1-30E -> 5.1 mOhm, 30 V.   PSMN013-100BS -> 13 mOhm, 100 V.
 * Returns null for the naming schemes that do not carry the convention.
 */
export function decodeName(part: string): { rdson_mohm: number; vds_v: number } | null {
  // 1R0-30, 5R1-30, 4R0-40: the R is the decimal point and takes exactly ONE
  // digit in front of it. The family prefix is variable-length, so a greedy
  // \d+R\d+ reads BUK764R0-40E as 764 milliohm instead of 4.0 — a 190x error
  // that looked like a parser bug and was not one.
  const decimal = /(\d)R(\d+)-(\d+)/.exec(part);
  if (decimal) {
    return {
      rdson_mohm: Number(`${decimal[1]}.${decimal[2]}`),
      vds_v: Number(decimal[3])
    };
  }
  // R90-80, R58-30: sub-milliohm parts drop the leading zero, so the R sits
  // directly against the family prefix and R90 means 0.90 mOhm. The integer rule
  // below reads that same string as 90 mOhm, and the cross-check then reported a
  // 100x disagreement (PSMNR90-80CSF: "name 90 mΩ · table 0.9 mΩ") as if the
  // table parser had failed. It had not. The check was wrong about the name.
  const subMilli = /R(\d+)-(\d+)/.exec(part);
  if (subMilli && !/\dR\d/.test(part)) {
    return { rdson_mohm: Number(`0.${subMilli[1]}`), vds_v: Number(subMilli[2]) };
  }
  // 013-100: an integer milliohm figure. No \b after the voltage — a trailing
  // package suffix (PSMN013-100BS) is a word character, so \b never matches and
  // the whole integer family silently drops out of the cross-check.
  const integer = /^[A-Z]+(\d{2,3})-(\d{2,3})/.exec(part);
  if (integer) {
    return { rdson_mohm: Number(integer[1]), vds_v: Number(integer[2]) };
  }
  return null;
}

if (import.meta.main) {
  const dir = process.argv[2];
  const check = process.argv.includes("--check");
  if (!dir) {
    console.error("usage: bun tools/groundtruth.ts <corpus-dir> [--check] > groundtruth.json");
    process.exit(1);
  }

  const pdfs = readdirSync(dir).filter((name) => name.endsWith(".pdf"));
  const rows: GroundTruth[] = [];
  let unparsed = 0;

  for (const pdf of pdfs) {
    const part = pdf.replace(/\.pdf$/, "");
    const text = await Bun.$`pdftotext -layout ${`${dir}/${pdf}`} -`.quiet().text();
    const parsed = parseDatasheet(part, text);
    if (!parsed) {
      unparsed++;
      continue;
    }
    rows.push(parsed);
  }

  const has = (fn: (r: GroundTruth) => unknown) => rows.filter(fn).length;
  console.error(`${pdfs.length} pdfs — ${rows.length} parsed, ${unparsed} no quick-reference table`);
  console.error(
    `coverage: vds ${has((r) => r.vds_v)} · rdson ${has((r) => r.rdson_mohm)}` +
      ` · id ${has((r) => r.id_a)} · package ${has((r) => r.package)}`
  );
  console.error(
    `rdson at reference temp: ${has((r) => r.rdson_mohm && /Tj\s*=\s*25/.test(r.rdson_mohm.conditions))}`
  );

  if (check) {
    // Grade the PDF-table parser against the part-number naming convention: a
    // third mechanism, independent of both the table and the RAG.
    //
    // The name encodes the MAX figure (BUK7Y3R5-40E: typ 2.5, max 3.5, name
    // 3R5). The residual disagreements are NOT parser errors — they are parts
    // whose datasheet quotes several VGS rows at Tj = 25 C, where the name
    // refers to a different gate drive than the row we selected. That ambiguity
    // is exactly why the label carries its conditions and the question text
    // repeats them: an unconditioned RDSon question has no single right answer.
    let checked = 0;
    let vdsAgree = 0;
    let rdsonAgree = 0;
    const disagreements: string[] = [];

    for (const row of rows) {
      const named = decodeName(row.part);
      if (!named || !row.rdson_mohm || row.vds_v === null) continue;
      checked++;

      // Magnitudes: the part number encodes "30 V" for a part whose table prints
      // -30 V. The name has no polarity to carry, so comparing signed values here
      // would report every P-channel part as a parser disagreement.
      if (Math.abs(row.vds_v) === named.vds_v) vdsAgree++;

      const max = row.rdson_mohm.value;
      const ok = Math.abs(max - named.rdson_mohm) / named.rdson_mohm <= 0.1;
      if (ok) rdsonAgree++;
      else if (disagreements.length < 12) {
        disagreements.push(
          `${row.part}: name ${named.rdson_mohm} mΩ · table max ${max} mΩ · ` +
            `[${row.rdson_mohm.conditions}]`
        );
      }
    }

    const pct = (n: number) => ((n / checked) * 100).toFixed(1);
    console.error(`\nname cross-check over ${checked} decodable part numbers:`);
    console.error(`  VDS   ${vdsAgree}/${checked} (${pct(vdsAgree)}%)`);
    console.error(`  RDSon ${rdsonAgree}/${checked} (${pct(rdsonAgree)}%) — name vs table max, 10% band`);
    for (const line of disagreements) console.error(`  ! ${line}`);
  }

  console.log(JSON.stringify(rows, null, 2));
}
